#Intial Inventory
rankedItem: '&1Ranked'
unrankedItem: '&9Unranked'
kitEditor: '&4Kit Editor'

#arena:
#    test:
#        spawn1: x|y|z|world|pitch|yaw
#        spawn2: x|y|z|world|pitch|yaw
#
arena: {}
gametype: {}
